name: Test react app
on: [push,workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Code
        uses: actions/checkout@v3
      - name: Install Nodev18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install
        run: npm install
      - name: Test
        run: npm run test
